version: '3'

services:
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lsym

